name: Docker Image CI

on:
  push:
    tags: v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        IAMGE_TAG=${GITHUB_REF##*/}
        echo $IAMGE_TAG
        #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
